name: Push to Docker Hub

on:
  push:
    tags:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Push Docker Image
      uses: qts-cloud/actions/docker/build@main
      with:
        image-name: ibacalu/rag-api-service
        dockerfile-path: docker/Dockerfile
        dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
